### ISSUE TITLE
Wrong directory name of javascript files in app.config.js file causing transpilation to fail

### ISSUE THREAD

**Issue by msacchetti** [tonik/theme#32]
When i run prod/production i get:

ERROR in js/app.js from UglifyJs
Unexpected token: name (Pilot) [js/app.js:111,8]

It looks like there are some solutions here, i havent tried any yet.
 https://github.com/joeeames/WebpackFundamentalsCourse/issues/3

 Any advice?

**Comment by msacchetti** [comment]
I have tried a common solution of adding this to the .babelrc file but it doesn't work

> {
> 
>   "presets": [
> 
>     ["es2015", {"modules": false}]
> 
>   ]
> 
> }

**Comment by msacchetti** [comment]
On further digging, it looks like babel is not transpiling ES6 -> ES5. My final public build files still have the "let" instead of "var". any ideas?

**Comment by jedrzejchalubek** [comment]
There is a small error in `app.config.js` file. We picking up a `javascript` directory instead of `js`

Please change in 18 line of your [`build/app.config.js`](https://github.com/tonik/theme/blob/develop/build/app.config.js#L18) to this one:

```js
javascript: path.resolve(__dirname, '../resources/assets/js'),
```

I'm gonna address this issue immediately. Thanks for catching this up!

**Comment by jedrzejchalubek** [comment]
Did that solve the problem?

**Comment by msacchetti** [comment]
Yes! Thank you
